- name: mongodb
  hosts: 44.203.95.104
  become: yes
  tasks:
  - name: setup mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: start and enable mongodb services
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: enable remote onnection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'


  - name: Restart mongodb services
    ansible.builtin.service:
      name: mongod
      state: restarted
  